id: D54C2F4A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:44:54+00:00'
last_modified: '2022-05-26T07:51:57.122943+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2886':
      image_group_id: I1PD95863
      title: རིམ་པ་ལྔ་པ།
      total_pages: 1634
      order: 18
      base_file: 2886.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
