id: P9CFAAA6D
initial_creation_type: ocr
source_metadata:
  volumes:
    ad578d3c51a740c49c823a3159cef114:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: རིམ་པ་ལྔ་པ།
      total_pages: 2069
      volume_number: 5
